# Generated by Django 4.0.4 on 2022-07-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.TextField(null=True)),
                ('video_id', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
